### ISSUE TITLE
call_user_func() expects non-static method

### ISSUE THREAD

**Issue by marquesine** [thecodeholic/php-mvc-framework#2]
Why is that? Is it part of the last PHP 7.4 updates?

Setting `public static funcion` won't cause any future problems?

Also, it is curious that the error is pointed, but the return of the function still appears below it.

![Screenshot_2021-02-23 Screenshot](https://user-images.githubusercontent.com/67472078/108889514-3b71a500-75eb-11eb-99bd-52b5af47e873.png)

Isn't it better to instatiate SiteController, then call for it? 

As follows:

`$siteController = new SiteController();`
`$app->router->get('/contact', [$siteController, 'contact']);`

**Comment by thecodeholic** [comment]
You should not set `public static function` because you won't be able to use `$this` keywork inside controller methods.

I think you don't have latest version of the code.
In latest version it automatically instantiates controller instance and uses that.
https://github.com/thecodeholic/tc-php-mvc-core/blob/master/Router.php#L55

**Comment by marquesine** [comment]
Still curious about why it claims it has to be a static method inside call_user_func().

I'll keep trying. So far, I have followed the tutorial by baby steps, and there it is working without the error.

**Comment by marquesine** [comment]
Now I see the problem. @thecodeholic himself correct it around 1:11:15 of the freeCodeCamp.org youtube video.
